Repository ScienceForChange/SoundCollect_dashboard, pull requests merged in 2024-07, with the labels that each got.

#96 Delete null genre value
  src/app/modules/soundscape/soundscape.module.ts
  src/app/services/observations/observations.service.ts
Labels: bug

#98 Updated with the new requirements
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.html
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.scss
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
Labels: enhancement

#99 Created and tested with the temporal-evolution-sound-level-chart
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.html
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.scss
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
  src/app/modules/soundscape/page/soundscape.component.html
  src/utils/energeticAvg.ts
  src/utils/index.ts
Labels: enhancement

#103 Front/fix/charts
  src/app/modules/soundscape/components/perception-chart/perception-chart.component.ts
  src/app/modules/soundscape/components/sound-levels-chart/sound-levels-chart.component.ts
  src/app/modules/soundscape/components/sound-types-chart/sound-types-chart.component.ts
  src/app/modules/soundscape/page/soundscape.component.ts
Labels: bug

#116 Solved. The first value as observation comes as empty array
  .vscode/settings.json
  src/app/modules/map/components/filters/filters.component.ts
  src/app/modules/map/components/laeq-tchart/laeq-tchart.component.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
Labels: bug

#119 Fixed
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
Labels: bug

#120 Added an error msg and translated
  src/app/modules/login/login.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#131 correción de actualización de la gráfica
  src/app/modules/soundscape/components/tag-cloud/tag-cloud.component.ts
Labels: bug

#134 Updated to work with no observations returned from polygon
  .vscode/settings.json
  src/app/modules/overview/components/bar-chart/bar-chart.component.html
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.html
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
Labels: bug

#150 Fixed
  src/app/modules/map/page/map.component.html
Labels: bug

#151 Created pipe for that string logic display of sound pressure
  src/app/modules/map/components/filters/filters.component.html
  src/app/modules/map/map.module.ts
  src/app/pipes/gender.pipe.spec.ts
  src/app/pipes/sound-pressure-display.pipe.ts
Labels: enhancement

#152 Ordered
  src/app/modules/map/components/filters/filters.component.html
Labels: enhancement

#153 Frontend/#140
  src/assets/i18n/ca.json
Labels: enhancement

#154 Updated
  src/app/modules/overview/components/observation-numbers/observation-numbers.component.html
Labels: bug

#155 Updated
  src/assets/i18n/ca.json
Labels: enhancement

#156 Created toggle style button at map section 3
  src/app/modules/soundscape/page/soundscape.component.html
  src/app/modules/soundscape/page/soundscape.component.scss
  src/app/modules/soundscape/page/soundscape.component.ts
  src/app/modules/soundscape/soundscape.module.ts
  src/styles/_buttons.scss
Labels: enhancement

#157 Changed at radiusAxis the maximum value to 80
  src/app/modules/soundscape/components/sound-levels-chart/sound-levels-chart.component.ts
Labels: enhancement

#159 Updated
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.ts
  src/app/modules/soundscape/components/sound-levels-chart/sound-levels-chart.component.ts
  src/app/modules/soundscape/components/tonal-frequency-chart/tonal-frequency-chart.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#161 Frontend/#142
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#164 Updated the Axis and the hour at tooltip
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
Labels: enhancement

#165 Update
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/app/modules/soundscape/components/tag-cloud/tag-cloud.component.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#166 Added the count of obs for each candel and added the translations to the tooltip
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#167 Correcciones Perception Chart
  src/app/modules/soundscape/components/perception-chart/perception-chart.component.ts
  src/assets/i18n/ca.json
Labels: bug

#170 Done
  src/app/modules/map/components/laeq-tchart/laeq-tchart.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#174 Mocked
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.ts
Labels: enhancement

#171 Bugs solucionados
  src/app/modules/map/components/laeq-tchart/laeq-tchart.component.ts
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.ts
  src/app/modules/soundscape/components/perception-chart/perception-chart.component.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
  src/app/modules/soundscape/components/tonal-frequency-chart/tonal-frequency-chart.component.ts
  src/assets/i18n/ca.json
Labels: bug

#175 Fixed the count when filtering
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
Labels: bug

#180 Frontend/#137
  src/app/modules/map/components/filters/filters.component.html
  src/app/shared/components/slider-step/slider-step.component.html
  src/app/shared/components/slider-step/slider-step.component.scss
  src/app/shared/components/slider-step/slider-step.component.spec.ts
  src/app/shared/components/slider-step/slider-step.component.ts
  src/app/shared/shared.module.ts
  src/styles/_inputs.scss
Labels: enhancement

#183 Upload step range
  src/app/modules/map/components/filters/filters.component.html
  src/app/shared/components/slider-step/slider-step.component.html
  src/app/shared/components/slider-step/slider-step.component.ts
Labels: enhancement

#184 Frontend/order imports
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/guards/auth.guard.ts
  src/app/interceptor/auth.interceptor.spec.ts
  src/app/interceptor/auth.interceptor.ts
  src/app/interceptor/error.interceptor.ts
  src/app/layout/app.layout.module.ts
  src/app/layout/components/footer/app.footer.component.html
  src/app/layout/components/footer/app.footer.component.ts
  src/app/layout/components/layout/app.layout.component.ts
  src/app/layout/components/menu/app.menu.component.html
  src/app/layout/components/menu/app.menu.service.ts
  src/app/models/map.ts
  src/app/modules/error/error.module.ts
  src/app/modules/error/page/error.component.ts
  src/app/modules/login/login.component.ts
  src/app/modules/login/login.module.ts
  src/app/modules/map/components/filters/filters.component.scss
  src/app/modules/map/components/filters/filters.component.ts
  src/app/modules/map/components/laeq-tchart/laeq-tchart.component.scss
  src/app/modules/map/components/laeq-tchart/laeq-tchart.component.ts
  src/app/modules/map/components/map-layers/map-layers.component.scss
  src/app/modules/map/components/map-layers/map-layers.component.ts
  src/app/modules/map/components/observation-info-modal/observation-info-modal.component.ts
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.scss
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.ts
  src/app/modules/map/components/tool-bar/tool-bar.component.scss
  src/app/modules/map/map.module.ts
  src/app/modules/map/page/map.component.ts
  src/app/modules/map/service/map.service.ts
  src/app/modules/overview/components/bar-chart/bar-chart.component.scss
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/app/modules/overview/components/catalunya-map/catalunya-map.component.scss
  src/app/modules/overview/components/catalunya-map/catalunya-map.component.ts
  src/app/modules/overview/components/observation-numbers/observation-numbers.component.ts
  src/app/modules/overview/overview.module.ts
  src/app/modules/profile/components/profile/profile.component.html
  src/app/modules/profile/components/profile/profile.component.scss
  src/app/modules/profile/components/profile/profile.component.spec.ts
  src/app/modules/profile/components/profile/profile.component.ts
  src/app/modules/profile/profile.module.ts
  src/app/modules/soundscape/components/perception-chart/perception-chart.component.ts
  src/app/modules/soundscape/components/pressure-chart/pressure-chart.component.ts
  src/app/modules/soundscape/components/qualitative-data-chart/qualitative-data-chart.component.ts
  src/app/modules/soundscape/components/quas-chart/quas-chart.component.ts
  src/app/modules/soundscape/components/sound-levels-chart/sound-levels-chart.component.ts
  src/app/modules/soundscape/components/sound-types-chart/sound-types-chart.component.ts
  src/app/modules/soundscape/components/tag-cloud/tag-cloud.component.ts
  src/app/modules/soundscape/components/tonal-frequency-chart/tonal-frequency-chart.component.ts
  src/app/modules/soundscape/page/soundscape.component.scss
  src/app/modules/soundscape/page/soundscape.component.ts
  src/app/modules/soundscape/soundscape.module.ts
  src/app/services/auth/auth.service.ts
  src/app/services/observations/observations.service.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#188 Frontend/#129
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/app/guards/auth.guard.spec.ts
  src/app/modules/error/page/error.component.spec.ts
  src/app/modules/login/login.component.spec.ts
  src/app/modules/map/components/filters/filters.component.spec.ts
  src/app/modules/map/components/laeq-tchart/laeq-tchart.component.spec.ts
  src/app/modules/map/components/map-layers/map-layers.component.spec.ts
  src/app/modules/map/components/observation-info-modal/observation-info-modal.component.spec.ts
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.spec.ts
  src/app/modules/map/components/tool-bar/tool-bar.component.spec.ts
  src/app/modules/map/page/map.component.spec.ts
  src/app/modules/map/page/map.component.ts
  src/app/modules/map/service/map.service.spec.ts
  src/app/modules/overview/components/bar-chart/bar-chart.component.spec.ts
  src/app/modules/overview/components/catalunya-map/catalunya-map.component.spec.ts
  src/app/modules/overview/components/observation-numbers/observation-numbers.component.spec.ts
  src/app/modules/overview/page/overview/overview.component.spec.ts
  src/app/modules/soundscape/components/tag-cloud/tag-cloud.component.spec.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.spec.ts
  src/app/modules/soundscape/components/tonal-frequency-chart/tonal-frequency-chart.component.spec.ts
  src/app/modules/soundscape/page/soundscape.component.spec.ts
  src/app/modules/soundscape/page/soundscape.component.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/observations/observations.service.spec.ts
  src/app/shared/components/slider-step/slider-step.component.spec.ts
  src/app/shared/components/spinner/spinner.component.spec.ts
  tsconfig.json
Labels: enhancement

#192 Front/fix/charts
  src/app/modules/soundscape/components/tag-cloud/tag-cloud.component.ts
Labels: bug

#194 corrección error en filtro de poligono al cambiar de sección
  src/app/modules/map/service/map.service.ts
Labels: bug

#200 Frontend/#189
  README.md
  src/app/modules/overview/components/bar-chart/bar-chart.component.html
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/app/services/observations/observations.service.ts
  src/assets/i18n/ca.json
Labels: enhancement

#203 Toggle popups
  src/app/modules/map/components/filters/filters.component.ts
  src/app/modules/map/components/tool-bar/tool-bar.component.ts
Labels: enhancement

#211 Frontend/#210
  src/app/app.module.ts
  src/app/handler/global-error-handler.ts
  src/app/modules/map/page/map.component.ts
  src/app/modules/map/service/map.service.ts
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/app/modules/overview/components/catalunya-map/catalunya-map.component.ts
  src/app/modules/overview/components/observation-numbers/observation-numbers.component.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
  src/app/services/observations/observations.service.ts
  src/assets/i18n/ca.json
Labels: bug, enhancement

#212 Refactor global variables
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
Labels: enhancement

#214 Frontend/fix/error handler
  src/app/handler/global-error-handler.ts
  src/app/modules/map/service/map.service.ts
  src/app/modules/overview/components/bar-chart/bar-chart.component.html
  src/app/modules/overview/components/bar-chart/bar-chart.component.ts
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.ts
  src/app/services/observations/observations.service.ts
Labels: bug

#222 Frontend/#7
  src/app/handler/global-error-handler.ts
  src/app/models/forms.ts
  src/app/models/map.ts
  src/app/modules/map/components/filters/filters.component.html
  src/app/modules/map/components/filters/filters.component.ts
  src/app/modules/map/service/map.service.ts
  src/assets/i18n/ca.json
Labels: enhancement

#223 Filtro de zonas con influencia positiva
  src/app/handler/global-error-handler.ts
  src/app/models/forms.ts
  src/app/models/map.ts
  src/app/modules/map/components/filters/filters.component.html
  src/app/modules/map/components/filters/filters.component.ts
  src/app/modules/map/service/map.service.ts
  src/assets/i18n/ca.json
Labels: enhancement

#224 Updated legend and Yaxis 1/3 octava
  src/app/modules/map/components/one-third-octave-chart/one-third-octave-chart.component.ts
  src/app/modules/soundscape/components/tonal-frequency-chart/tonal-frequency-chart.component.ts
  src/assets/i18n/ca.json
Labels: enhancement

#225 Added
  src/assets/i18n/ca.json
Labels: enhancement

#229 Updated
  src/app/modules/home/page/home.component.html
  src/assets/i18n/ca.json
Labels: enhancement

#230 Done
  src/app/app-routing.module.ts
  src/app/layout/components/menu/app.menu.component.html
  src/assets/i18n/ca.json
Labels: enhancement

#232 Front/feature/info modal#182
  src/app/modules/overview/components/bar-chart/bar-chart.component.html
  src/app/modules/soundscape/components/perception-chart/perception-chart.component.html
  src/app/modules/soundscape/components/pressure-chart/pressure-chart.component.html
  src/app/modules/soundscape/components/qualitative-data-chart/qualitative-data-chart.component.html
  src/app/modules/soundscape/components/quas-chart/quas-chart.component.html
  src/app/modules/soundscape/components/sound-levels-chart/sound-levels-chart.component.html
  src/app/modules/soundscape/components/sound-types-chart/sound-types-chart.component.html
  src/app/modules/soundscape/components/tag-cloud/tag-cloud.component.html
  src/app/modules/soundscape/components/temporal-evolution-sound-level-chart/temporal-evolution-sound-level-chart.component.html
  src/app/modules/soundscape/components/tonal-frequency-chart/tonal-frequency-chart.component.html
  src/app/shared/components/info-modal/info-modal.component.html
  src/app/shared/components/info-modal/info-modal.component.scss
  src/app/shared/components/info-modal/info-modal.component.spec.ts
  src/app/shared/components/info-modal/info-modal.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#233 Repositioned
  src/app/modules/soundscape/page/soundscape.component.html
  src/assets/i18n/ca.json
Labels: enhancement

#236 Updated
  src/assets/i18n/ca.json
Labels: bug, enhancement

#237 Update dBa to dBA
  src/assets/i18n/ca.json
Labels: enhancement

#247 Changed
  src/app/modules/soundscape/page/soundscape.component.html
Labels: enhancement
